### ISSUE TITLE
put in place Configuration Management with Ansible

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/deployment#17]
- [x] list which Nagios checks are to be kept and how to migrate them to Ansible
 - [x] deploy a VM in Exoscale and install Ansible (follow the guide from https://github.com/SixSq/tasklist/issues/1378)
 - [x] configure AWX and add the Nuvla CM into it
 - [x] Nuvla check in write mode like try to login and to set Grafana alerts on disk low and cpu ram monitoring
 - [x] add the "Nagios" checks before 2020

**Comment by cjdcordeiro** [comment]
@konstan what do u think?

## Nagios checks ...

#### to keep
 - es6-01.nuv.la*
 - fed-id.nuv.la* (low priority)
 - localhost*
 - nuv.la* (move to nuvla.io and remove the check below)
 - sixsq.com
 - support.sixsq.com


 and new ones to add, TBD later
   
#### to go away

 - api.github.com*
 - nuv.la
    - Check metering service
    - HSQLDB
    - NRPE_5666
    - SS-LOGIN_AUTH
    - ss-exec*
 - nuvlabox*
 - ssdocs.sixsq.com* (to be replaces by docs.nuvla.io)
 - ssapi.sixsq.com* (should also be replaced at some point)

**Comment by konstan** [comment]
@cjdcordeiro  LGTM. 

Checks should be on host and service levels.

To add:
* vpn.nuvlabox.com

**Comment by cjdcordeiro** [comment]
sixsq.com and support.sixsq.com done

**Comment by cjdcordeiro** [comment]
docs.nuvla.io has been added, which means the other ss and api docs will not be migrated, and shall be removed whenever nuv.la is decommissioned

**Comment by cjdcordeiro** [comment]
localhost system checks have been added for phoenix

**Comment by cjdcordeiro** [comment]
migrated fed-id checks

**Comment by konstan** [comment]
This was done. Closing.
