### ISSUE TITLE
create complete docker-compose nuvla deployments

### ISSUE THREAD

**Issue by loomis** [nuvla/deployment#4]
Create complete docker-compose nuvla deployments. All these should include traefik as the outward facing load balancer and proxy for the system. The system should route requests as follows:

 - `http://nuvla-host.org/`: redirects to `http://nuvla-host.org/ui`
 - `http://nuvla-host.org/ui/*`: routes to the UI container(s)
 - `http://nuvla-host.org/api/*`: routes to the API container(s)

The test deployments should allow both unsecured (http) and secured (https) systems. The production deployment should allow only secured systems with real certificates (likely from Let's Encrypt).

**Comment by cjdcordeiro** [comment]
the Traefik conf to let it handle LE certs by itself is here: https://github.com/slipstream/SlipStreamServer/blob/master/cimi-deployment/traefik/traefik_https.toml

**Comment by konstan** [comment]
Unfortunately,  `/*` to `/ui` route, when `/api` is not available, redirects requests to `/api` to `/ui`. See https://github.com/nuvla/deployment/issues/5

**Comment by loomis** [comment]
The routes have been changed to:
```
PathPrefix:/api
```
and 
```
Path:/,/{a:.},/{b:..},/{c:ui.*},/{d:([^a][^p][^i]|a[^p].|a.[^i]|[^a]p.|.p[^i]|[^a].i|.[^p]i).*}
```
If effectively routes anything that doesn't start with `/api` to the ui container. For the record:

 - Using a `PathPrefix:/*` with a priority doesn't work because it will match `/api` for the ui when the api service is unhealthy. (Hence causing the `/api/cloud-entry-point` to return successfully with HTML rather than JSON.)
 - The tortured path syntax is because the go RE2 regular expression library doesn't support negative lookaheads and the PathPrefix regex expression don't appear to support embedded braces like `/{a:.{0,2}}`. 

The important part of this change is that requests to the root of the server will redirect to the ui.

**Comment by loomis** [comment]
To allow for "pluggable" services (e.g. monitoring) in production deployments, the routing has been changed to the following:

 - ui container for "/", "/ui/", and "/ui.*" paths and 
 - api container for "/api.*"

This allows new services to be added dynamically without interference from the old UI routing.

**Comment by loomis** [comment]
The test, demo, and prod deployments have been updated and documented.
